API_KEY = 'your_api_key_here'
API_SECRET_KEY = 'your_api_secret_key_here'
ACCESS_TOKEN = 'your_access_token_here'
ACCESS_TOKEN_SECRET = 'your_access_token_secret_here'
BEARER_TOKEN = 'your_bearer_token_here'
INFURA_URL = 'your_infura_project_url'
PRIVATE_KEY = 'your_private_key_here'
